package rules

import com.huawei.client.provider.subprovider.vo.TestVo;

rule subBackNumsPoint
	// 发生退货，扣减10分
	salience 10
	lock-on-active true
	when
		$testVo : TestVo(backNums >= 1)
	then
		$testVo.setPoint($testVo.getPoint()-10);
		$testVo.recordPointLog($testVo.getUserName(),"subBackNums");
end

rule subBackMondyPoint
	// 退货金额大于100，扣减100分
	salience 9
	lock-on-active true
	when
		$testVo : TestVo(backMondy >= 100)
	then
		$testVo.setPoint($testVo.getPoint()-10);
		$testVo.recordPointLog($testVo.getUserName(),"subBackMondy");
end